export const FILE_TRANSFER_DEFAULT_CHUNK_SIZE = 8 * 1024 * 1024;
export const FILE_TRANSFER_DOWNLOAD_CHUNK_TIMEOUT_MS = 120_000;
export const FILE_TRANSFER_UPLOAD_CHUNK_TIMEOUT_MS = 300_000;
export const ARCHIVE_STATUS_POLL_INTERVAL_MS = 1_500;
export const MAX_IN_MEMORY_DOWNLOAD_BYTES = 512 * 1024 * 1024;
export const FILE_TRANSFER_UPLOAD_RESUME_LS_KEY = "trmm-resume-up";
export const FILE_TRANSFER_DOWNLOAD_RESUME_LS_KEY = "trmm-resume-dl";
export const FILE_TRANSFER_DOWNLOAD_IDB_NAME = "trmm-transfer";
export const FILE_TRANSFER_DOWNLOAD_IDB_STORE = "handles";
export const FILE_TRANSFER_UI_META_IDB_STORE = "ui_meta";
export const FILE_TRANSFER_IDB_VERSION = 2;
export const FILE_TRANSFER_LOCAL_PAUSED_LS_KEY = "trmm-transfer-local-paused";
export const FILE_TRANSFER_TAB_SYNC_CHANNEL = "trmm-file-transfer-tab-sync";
export const FILE_TRANSFER_TAB_SYNC_HEARTBEAT_MS = 5_000;
export const FILE_TRANSFER_TAB_SYNC_STALE_MS = 15_000;
export const FILE_TRANSFER_SLOT_RETRY_BASE_MS = 2_000;
export const FILE_TRANSFER_SLOT_RETRY_MAX_MS = 30_000;
export const TRANSFER_SLOT_WAIT_MESSAGE =
  "Waiting for a free transfer slot. Cancel or finish a paused transfer to continue.";
