export const MAX_UPLOAD_FILE_SIZE_BYTES = 0;
export const MAX_UPLOAD_FILES_PER_SELECTION = 100;
export const MAX_UPLOAD_QUEUE_ITEMS = 500;
export const MAX_DELETE_PATHS_PER_REQUEST = 100;
export const MAX_SEQUENTIAL_DOWNLOAD_FILES = 10;
export const MAX_DOWNLOAD_QUEUE_ITEMS = 100;
export const MAX_ARCHIVE_PATHS = 100;
export const ARCHIVE_PREPARE_TIMEOUT_MS = 3_600_000;

export const FILE_BROWSER_MAX_NAME_LENGTH = 255;
export const FILE_BROWSER_INVALID_NAME_CHARS = /[\\/:*?"<>|\x00-\x1f]/;
